Webdaugia/Webdaugia/Models/Common/AdLot.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Webdaugia.Models.Common
{
    public class AdLot
    {

        public int? ID { get; set; }
        [Required(ErrorMessage = "Bạn cần nhập tên phiên đấu giá")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Bạn  cần nhập bước giá")]
        public long? MiniumBid { get; set; }
        [Required(ErrorMessage = "Bạn cần nhập giá khởi điểm")]
        public long? StartingPrice { get; set; }
        [Required(ErrorMessage = "Bạn cần nhập tiền cọc")]
        public long? AdvanceDesposit { get; set; }
        [Required(ErrorMessage = "Bạn cần nhập phí tham gia")]
        public int? ParticipationFee { get; set; }

        public int? HostLot { get; set; }

        [Required(ErrorMessage = "Bạn cần nhập ngày kết thúc đăng ký")]
        public DateTime? TimeForRegisterEnd { get; set; }

        [Required(ErrorMessage = "Bạn cần nhập ngày bắt đầu đấu giá")]
        public DateTime? TimeForBidEnd { get; set; }

        [Required(ErrorMessage = "Bạn cần nhập ngày kết thúc đấu giá")]

        public DateTime? TimeForBidStart { get; set; }

        [Required(ErrorMessage = "Bạn cần nhập ngày bắt đầu đăng ký")]
        public DateTime? TimeForRegisterStart { get; set; }


        public bool? Status { get; set; }
        [Required(ErrorMessage = "Vui lòng chọn thể loại đấu giá")]
        public int? CateID { get; set; }


        [StringLength(200)]
        [Required(ErrorMessage = "Vui lòng nhập chủ tài sản")]
        public string HostName { get; set; }

        [StringLength(158)]
        [Required(ErrorMessage = "Vui lòng nhập địa chỉ")]
        public string Location { get; set; }

        [StringLength(158)]
        [Required(ErrorMessage = "Vui lòng nhập thời gian xem sản phẩm")]
        public string ViewInTime { get; set; }

        public string LotImage;
        [Required(ErrorMessage = "Vui lòng chọn ảnh")]
        public HttpPostedFileBase file1 { get; set; }

        public List<Category> ListCategory = new List<Category>();

    }
}

Webdaugia/Webdaugia/Areas/Admin/Controllers/AdLotController.cs
using Webdaugia.Models;
using Webdaugia.Models.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using Webdaugia.DAO;
using System.IO;

using System.Data.Entity.Migrations;
using System.Threading.Tasks;

namespace Webdaugia.Areas.Admin.Controllers
{
    [HandleError]
    public class AdLotController : Controller

    {

        string FilePath = "";
        public ActionResult Index()
        {
            if (Session["AD"] == null)
            {
                return RedirectToAction("Index", "AdLogin");
            }
            else
            {
                return View();
            }

        }
        // GET: Admin/Lot
        AuctionDBContext db = null;
        public ActionResult ListLot(string searchString, int page = 1, int pageSize = 10)
        {
            if (Session["AD"] == null)
            {
                return RedirectToAction("Index", "AdLogin");
            }
            else
            {

                var user = (UserLogin)Session["AD"];
                var dao = new LotDao();
                var model = user.Role == 2 ? dao.ListAllPaging2(user.UserID, searchString, page, pageSize) : dao.ListAllPaging(searchString, page, pageSize);
                ViewBag.searchString = searchString;
                return View(model);
            }

        }
        public ActionResult ListLotAuction(string searchString, int page = 1, int pageSize = 10)
        {
            var user = (UserLogin)Session["AD"];
            if (Session["AD"] == null)
            {
                return RedirectToAction("Index", "AdLogin");
            }
            else
            {
                var dao = new LotDao();
                var model = user.Role == 2 ? dao.ListAllPagingAuction2(user.UserID,searchString, page, pageSize)  : dao.ListAllPagingAuction(searchString, page, pageSize);
                ViewBag.searchString = searchString;
                return View(model);
            }

        }

        public ActionResult ListAuctionOfLot(int id, string searchString, int page = 1, int pageSize = 10)
        {
            var user = (UserLogin)Session["AD"];
            if (Session["AD"] == null)
            {
                return RedirectToAction("Index", "AdLogin");
            }
            else
            {
                var dao = new LotDao();
                
                if(user.Role == 2 && dao.ViewDetail(id).HostLot != user.UserID)
                {
                     return RedirectToAction("ListLotAuction");
                }
                var model = dao.ListAllPagingAuctionOfLot(id, searchString, page, pageSize);

                ViewBag.LotId = id;
                ViewBag.searchString = searchString;
                return View(model);
            }

        }
        public ActionResult ListLotRegister(string searchString, int page = 1, int pageSize = 10)
        {
            var user = (UserLogin)Session["AD"];
            if (Session["AD"] == null)
            {
                return RedirectToAction("Index", "AdLogin");
            }
            else
            {
                var dao = new LotDao();
                var model = user.Role == 2 ? dao.ListAllPagingRegister2(user.UserID, searchString, page, pageSize) : dao.ListAllPagingRegister(searchString, page, pageSize);
                ViewBag.searchString = searchString;
                return View(model);
            }

        }
        public ActionResult ListUserEndOfLot(int id, string searchString, int page = 1, int pageSize = 10)
        {
            if (Session["AD"] == null)
            {
                return RedirectToAction("Index", "AdLogin");
            }
            else
            {


                db = new AuctionDBContext();

                var user = (UserLogin)Session["AD"];
                if (user.Role == 2)
                {
                    var lot = db.Lots.Where(x => x.ID == id && x.HostLot == user.UserID).SingleOrDefault();
                    if (lot == null)
                    {
                        return RedirectToAction("ListLotEnd");
                    }
                }
                var listATM = db.ATMs.ToList();
                List<ATM> listATMEnd = new List<ATM>();
                var dao = new LotDao();
                long? totalMoney = 0;
                long? Money = db.Lots.Where(x => x.ID == id).SingleOrDefault().AdvanceDesposit;
                var model = dao.ListAllPagingEndOfLot(id, searchString, page, pageSize);
                if(model != null)
                {
                    foreach (var item in model)
                    {
                        totalMoney += item.Lot.AdvanceDesposit;
                        var atm = listATM.Where(x => x.UserID == item.UserID).FirstOrDefault();
                        if (atm != null)
                        {
                            listATMEnd.Add(atm);
                        }
                    }
                }
                
                ViewBag.searchString = searchString;
                ViewBag.listATM = listATMEnd;
                ViewBag.totalMoney = totalMoney;
                ViewBag.Money = Money;
                return View(model);
            }

        }
        public ActionResult ListRegitsterOfLot(int id, string searchString, int page = 1, int pageSize = 10)
        {
            var user = (UserLogin)Session["AD"];
            if (Session["AD"] == null)
            {
                return RedirectToAction("Index", "AdLogin");
            }
            else
            {
                db = new AuctionDBContext();
                var lot = db.Lots.Find(id);
                if (user.Role == 2)
                {
                    var lot3 = db.Lots.Where(x => x.ID == id && x.HostLot == user.UserID).SingleOrDefault();
                    if (lot3 == null)
                    {
                        return RedirectToAction("ListLotRegister");
                    }
                }
                ViewBag.tiencoc = lot.ParticipationFee + lot.AdvanceDesposit;
                var dao = new LotDao();
                var model = dao.ListAllPagingRegisterOfLot(id, searchString, page, pageSize);
                ViewBag.searchString = searchString;
                ViewBag.LotId = id;
                return View(model);
            }

        }
        public ActionResult ListLotEnd(string searchString, int page = 1, int pageSize = 10)
        {
            var user = (UserLogin)Session["AD"];
            if (Session["AD"] == null)
            {
                return RedirectToAction("Index", "AdLogin");
            }
            else
            {
                var dao = new LotDao();
                var model = user.Role == 2 ? dao.ListAllPagingEnd2(user.UserID, searchString, page, pageSize) : dao.ListAllPagingEnd(searchString, page, pageSize);
                ViewBag.searchString = searchString;
                return View(model);
            }

        }
        public ActionResult ListLotEndFor180(string searchString, int page = 1, int pageSize = 10)
        {
            var user = (UserLogin)Session["AD"];
            if (Session["AD"] == null || user.Role == 2)
            {
                return RedirectToAction("Index", "AdLogin");
            }

            else
            {
                var dao = new LotDao();
                var model = dao.ListAllPagingEnd30(searchString, page, pageSize);
                ViewBag.searchString = searchString;
                return View(model);
            }

        }
        public ActionResult ListLotLink(string searchString, int page = 1, int pageSize = 10)
        {
            if (Session["AD"] == null)
            {
                return RedirectToAction("Index", "AdLogin");
            }
            else
            {
                var dao = new LotDao();
                var model = dao.ListAllPagingLink(searchString, page, pageSize);
                ViewBag.searchString = searchString;
                return View(model);
            }

        }
        public ActionResult DeleteLot(int id)
        {
            var user = (UserLogin)Session["AD"];
            if (Session["AD"] == null || user.Role == 2)
            {
                return RedirectToAction("Index", "AdLogin");
            }
            else
            {
                db = new AuctionDBContext();
                var date = DateTime.Now.AddDays(-180);

                var lot = db.Lots.Where(x => x.ID == id && x.TimeForBidEnd < date).SingleOrDefault();
                if (lot == null)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    var listproduct = db.Products.Where(x => x.LotID == lot.ID);
                    if (listproduct != null)
                    {
                        List<ProductsImage> listImage = new List<ProductsImage>();
                        foreach (var item in listproduct)
                        {
                            var listimg = db.ProductsImages.Where(x => x.ProductId == item.ID);
                            if (listimg != null)
                            {
                                listImage.AddRange(listimg);
                            }
                        }
                        if (listImage != null)
                        {
                            foreach (var item in listImage)
                            {
                                string path = Path.Combine(Server.MapPath(item.Image)); ;

                                if (!Directory.Exists(path))
                                {

                                    System.IO.File.Delete(path);
                                }
                            }
                            db.ProductsImages.RemoveRange(listImage);


                        }
                        db.Products.RemoveRange(listproduct);

Webdaugia/Webdaugia/Areas/Admin/Views/AdLot/CreateLink.cshtml
@model Webdaugia.Models.LotAttachment
@{
    ViewBag.Title = "CreateLink";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<div class="box">
    @using (Html.BeginForm("CreateLink", "AdLot", FormMethod.Post, new { @area = "Admin", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <div class="col-6">
            <a href="/admin/adlot/ListLotLink" class="btn btn-info" style="display:inline-block">
                Danh sách link đính kèm phiên đấu giá
            </a>
        </div>
        <div class="col-6">
            <div class="text-success" style="font-size:large">@ViewBag.success</div>
            <div class="text-danger" style="font-size:large">@ViewBag.error</div>
        </div>
        <div class="col-6">
            <label>Tên link đính kèm</label>
            <div class="form_control">
                @Html.TextBoxFor(model => model.Name, htmlAttributes: new { name = "Name", type = "text" })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-6">
            <label>Link đính kèm</label>
            <div class="form_control">
                @Html.TextBoxFor(model => model.AttachmentLink, htmlAttributes: new { name = "AttachmentLink", type = "text" })
         
                @Html.ValidationMessageFor(model => model.AttachmentLink, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-6">
            <label>ID Phiên</label>
            <div class="form_control">
                @Html.DropDownListFor(model => model.LotID, new SelectList(Model.ListLot, "Id", "Name"), "--Chọn phiên-- ", new { @Name = "LotID" })
                @Html.ValidationMessageFor(model => model.LotID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-6 col-12">

            <button class="btn btn-success" type="submit">Thêm mới đính kèm</button>

        </div>
    }
</div>

Webdaugia/Webdaugia/Areas/Admin/Views/AdLot/CreateLot.cshtml
@model Webdaugia.Models.Common.AdLot

@{
    ViewBag.Title = "AddProduct";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Thêm Sản Phẩm Mới</h2>
<div class="box">
    @using (Html.BeginForm("CreateLot", "AdLot", FormMethod.Post, new { @area = "Admin", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <div class="col-6 col-sm-12">
            <a href="/admin/adlot/listlot" class="btn btn-info" style="display:inline-block">
                Danh Sách Phiên Đấu Giá
            </a>
        </div>
        <div class="col-6 col-sm-12">
            <div class="text-success" style="font-size:large">@ViewBag.success</div>
            <div class="text-danger" style="font-size:large">@ViewBag.fail</div>
        </div>
        <div class="col-6 col-sm-12">
            <label>Tên phiên đấu giá</label>
            <div class="form_control">
                @Html.TextBoxFor(model => model.Name, htmlAttributes: new { name = "Name", type = "text" })
                @*   <input name="Name"
                    type="text" />*@
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-6 col-sm-12">
            <label>Chọn loại đấu giá</label>
            <div class="form_control">
                @Html.DropDownList("CateID", new SelectList(Model.ListCategory, "Id", "Name"), "--Chọn thể loại-- ")
                @*@Html.DropDownListFor(m => m.ListCategory, Model.ListCategory ?? new List<SelectListItem>(), "--Chọn Ngân hàng--")*@
                @*@Html.DropDownList("tennganhang", ViewBag.banks as SelectList, "--Chọn Ngân hàng-- ", new { @Name = "tennganhang" })*@
                @Html.ValidationMessageFor(model => model.CateID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-6 col-sm-12">
            <label>Giá khởi điểm</label>
            <div class="form_control">
                @Html.TextBoxFor(model => model.StartingPrice, htmlAttributes: new { name = "StartingPrice", type = "number" })
                @*  <input name="StartingPrice"
                    type="number" />*@
                @Html.ValidationMessageFor(model => model.StartingPrice, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-6 col-sm-12">
            <label>Bước giá</label>
            <div class="form_control">
                @Html.TextBoxFor(model => model.MiniumBid, htmlAttributes: new { name = "MiniumBid", type = "number" })
                @*         <input name="MiniumBid"
                    type="number" />*@
                @Html.ValidationMessageFor(model => model.MiniumBid, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-6 col-sm-12">
            <label>Tiền đặt trước</label>
            <div class="form_control">
                @Html.TextBoxFor(model => model.AdvanceDesposit, htmlAttributes: new { name = "AdvanceDesposit", type = "number" })
                @* <input name="AdvanceDesposit"
                    type="number" />*@
                @Html.ValidationMessageFor(model => model.AdvanceDesposit, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-6 col-sm-12">
            <label>Phí tham gia</label>
            <div class="form_control">
                @Html.TextBoxFor(model => model.ParticipationFee, htmlAttributes: new { name = "ParticipationFee", type = "number" })
                @*     <input name="ParticipationFee"
                    type="number" />*@
                @Html.ValidationMessageFor(model => model.ParticipationFee, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-6 col-sm-12">
            <label>Người có tài sản đấu giá</label>
            <div class="form_control">
                @Html.TextBoxFor(model => model.HostName, htmlAttributes: new { name = "ParticipationFee", type = "text" })
                @*            <input name="HostName"
                    type="text" />*@
                @Html.ValidationMessageFor(model => model.HostName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-6 col-sm-12">
            <label>Địa điểm xem tài sản</label>
            <div class="form_control">
                @Html.TextBoxFor(model => model.Location, htmlAttributes: new { name = "Location", type = "text" })
                @*           <input name="Location"
                    type="text" />*@
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-6 col-sm-12">
            <label>Thời gian xem tài sản </label>
            <div class="form_control">
                @Html.TextBoxFor(model => model.ViewInTime, htmlAttributes: new { name = "ViewInTime", type = "text" })
                @Html.ValidationMessageFor(model => model.ViewInTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-6 col-sm-12">
            <label>Ngày bắt đầu đăng ký phiên</label>
            <div class="form_control">
                @Html.TextBoxFor(model => model.TimeForRegisterStart, htmlAttributes: new { name = "TimeForRegisterStart", type = "datetime-local" })
                @*   <input name="TimeForRegisterStart"
                    type="datetime-local" />*@
                @Html.ValidationMessageFor(model => model.TimeForRegisterStart, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-6 col-sm-12">
            <label>Ngày kết thúc đăng ký phiên</label>
            <div class="form_control">
                @Html.TextBoxFor(model => model.TimeForRegisterEnd, htmlAttributes: new { name = "TimeForRegisterEnd", type = "datetime-local" })
                @*    <input name="TimeForRegisterEnd"
                    type="datetime-local" />*@
                @Html.ValidationMessageFor(model => model.TimeForRegisterEnd, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-6 col-sm-12">
            <label>Ngày bắt đầu phiên đấu giá</label>
            <div class="form_control">
                @Html.TextBoxFor(model => model.TimeForBidStart, htmlAttributes: new { name = "TimeForBidStart", type = "datetime-local" })
                @*         <input name="TimeForBidStart"
                    type="datetime-local" />*@
                @Html.ValidationMessageFor(model => model.TimeForBidStart, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-6 col-sm-12">
            <label>Ngày kết thúc phiên đấu giá</label>
            <div class="form_control">
                @Html.TextBoxFor(model => model.TimeForBidEnd, htmlAttributes: new { name = "TimeForBidEnd", type = "datetime-local" })
                @*         <input name="TimeForBidEnd"
                    type="datetime-local" />*@
                @Html.ValidationMessageFor(model => model.TimeForBidEnd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-6 col-sm-12">
            <label>Hình ảnh đại diện Phiên</label>

            <div class="form_control">
                @Html.TextBoxFor(model => model.file1, htmlAttributes: new { name = "file1", type = "file" })
                @*  <input type="file" name="file1" />*@
                @Html.ValidationMessageFor(model => model.file1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-6 col-sm-12 col-12">

            <button class="btn btn-success" type="submit">Thêm mới phiên đấu giá</button>

        </div>
    }
</div>

Webdaugia/Webdaugia/Areas/Admin/Views/AdLot/EditLink.cshtml
@model Webdaugia.Models.LotAttachment
@{
    ViewBag.Title = "EditLink";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="box">
    @using (Html.BeginForm("EditLink", "AdLot", FormMethod.Post, new { @area = "Admin", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <div class="col-6">
            <a href="/admin/adlot/ListLotLink" class="btn btn-info" style="display:inline-block">
                Danh sách link đính kèm phiên đấu giá
            </a>
        </div>
        <div class="col-6">
            <div class="text-success" style="font-size:large">@ViewBag.success</div>
            <div class="text-danger" style="font-size:large">@ViewBag.error</div>
        </div>
        <div class="col-6">
            <label>Tên link đính kèm</label>
            <div class="form_control">
                @Html.TextBoxFor(model => model.Name, htmlAttributes: new { name = "Name", type = "text" })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-6">
            <label>Link đính kèm</label>
            <div class="form_control">
                @Html.TextBoxFor(model => model.AttachmentLink, htmlAttributes: new { name = "AttachmentLink", type = "text" })

                @Html.ValidationMessageFor(model => model.AttachmentLink, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-6">
            <label>ID Phiên</label>
            <div class="form_control">
                @Html.DropDownListFor(model => model.LotID, new SelectList(Model.ListLot, "Id", "Name"), "--Chọn phiên-- ", new { @Name = "LotID" })
                @Html.ValidationMessageFor(model => model.LotID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-6 col-12">

            <button class="btn btn-success" type="submit">Sửa đính kèm</button>

        </div>
    }
</div>

Webdaugia/Webdaugia/Areas/Admin/Views/AdLot/EditLot.cshtml
@model Webdaugia.Models.Lot
@{
    ViewBag.Title = "EditLot";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Chỉnh Sửa Thông Tin Phiên Đấu Giá</h2>
<div class="box">
    @using (Html.BeginForm("EditLot", "AdLot", FormMethod.Post, new { @area = "Admin", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <div class="col-6">
            <a href="/admin/adlot/listlot" class="btn btn-info" style="display:inline-block">
                Danh Sách Phiên Đấu Giá
            </a>
        </div>

        <div class="col-6">
            <div class="text-success" style="font-size:large">@ViewBag.success</div>
            <div class="text-danger" style="font-size:large">@ViewBag.fail</div>
        </div>

        <div class="col-6">
            <label>Tên phiên đấu giá</label>
            <div class="form_control">
                <input required
                       name="Name"
                       type="text"
                       value="@Model.Name" />
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-6 col-sm-12">
            <label>Chọn loại đấu giá</label>
            <div class="form_control">
                @Html.DropDownList("CateID", new SelectList(Model.ListCategory, "Id", "Name"), "--Chọn thể loại-- ")
                @*@Html.DropDownListFor(m => m.ListCategory, Model.ListCategory ?? new List<SelectListItem>(), "--Chọn Ngân hàng--")*@
                @*@Html.DropDownList("tennganhang", ViewBag.banks as SelectList, "--Chọn Ngân hàng-- ", new { @Name = "tennganhang" })*@
                @Html.ValidationMessageFor(model => model.CateID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-6">
            <label>Giá khởi điểm</label>
            <div class="form_control">
                <input required
                       name="StartingPrice"
                       type="number"
                       value="@Model.StartingPrice" />
                @Html.ValidationMessageFor(model => model.StartingPrice, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-6">
            <label>Bước giá</label>
            <div class="form_control">
                <input required
                       name="MiniumBid"
                       type="number"
                       value="@Model.MiniumBid" />
                @Html.ValidationMessageFor(model => model.MiniumBid, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-6">
            <label>Giá đặt cọc</label>
            <div class="form_control">
                <input required
                       name="AdvanceDesposit"
                       type="number"
                       value="@Model.AdvanceDesposit" />
                @Html.ValidationMessageFor(model => model.AdvanceDesposit, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-6">
            <label>Tiền đặt trước</label>
            <div class="form_control">
                <input required
                       name="ParticipationFee"
                       type="number"
                       value="@Model.ParticipationFee" />
                @Html.ValidationMessageFor(model => model.ParticipationFee, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-6">
            <label>Chủ tài sản</label>
            <div class="form_control">
                <input required
                       name="HostName"
                       type="text"
                       value="@Model.HostName" />
                @Html.ValidationMessageFor(model => model.HostName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-6">
            <label>Địa điểm xem tài sản</label>
            <div class="form_control">
                <input required
                       name="Location"
                       type="text"
                       value="@Model.Location" />
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-6">
            <label>Thời gian xem sản phẩm đấu giá</label>
            <div class="form_control">
                <input required
                       name="ViewInTime"
                       type="text"
                       value="@Model.ViewInTime" />
                @Html.ValidationMessageFor(model => model.ViewInTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-6">
            <label>Ngày bắt đầu đăng ký phiên đấu giá</label>
            <div class="form_control">
                <input required
                       name="TimeForRegisterStart"
                       type="datetime-local"
                       value="@Model.TimeForRegisterStart.Value.ToString("yyyy-MM-ddTHH:mm")" />
                @Html.ValidationMessageFor(model => model.TimeForRegisterStart, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-6">
            <label>Ngày kết thúc đăng ký phiên</label>
            <div class="form_control">
                <input required
                       name="TimeForRegisterEnd"
                       type="datetime-local"
                       value="@Model.TimeForRegisterEnd.Value.ToString("yyyy-MM-ddTHH:mm")" />
                @Html.ValidationMessageFor(model => model.TimeForRegisterEnd, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-6">
            <label>Ngày bắt đầu phiên đấu giá</label>
            <div class="form_control">
                <input required
                       name="TimeForBidStart"
                       type="datetime-local"
                       value="@Model.TimeForBidStart.Value.ToString("yyyy-MM-ddTHH:mm")" />
                @Html.ValidationMessageFor(model => model.TimeForBidStart, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-6">
            <label>Ngày kết thúc phiên đấu giá</label>
            <div class="form_control">
                <input required
                       name="TimeForBidEnd"
                       type="datetime-local"
                       value="@Model.TimeForBidEnd.Value.ToString("yyyy-MM-ddTHH:mm")" />
                @Html.ValidationMessageFor(model => model.TimeForBidEnd, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-6">
            <label>Hình ảnh đại diện Phiên</label>
            <div class="form_control">
                <img src="@Model.LotImage" width="100px" />
                <input type="file" name="file1" />
            </div>
        </div>

        <div class="col-6 col-12">

            <button class="btn btn-success" type="submit">Sửa phiên đấu giá mới</button>

        </div>
    }
</div>