Webdaugia/Webdaugia/Areas/Admin/Controllers/AdProductController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Webdaugia.DAO;
using Webdaugia.Models;
using Webdaugia.Models.Common;

namespace Webdaugia.Areas.Admin.Controllers
{
    [HandleError]
    public class AdProductController : Controller
    {
   
        string FilePath = "";
        public ActionResult Index()
        {
            if (Session["AD"] == null)
            {
                return RedirectToAction("Index", "AdLogin");
            }
            return View();
        }
        // GET: Admin/Product
        AuctionDBContext db = null;
        public ActionResult ListProduct(string searchString, int page = 1, int pageSize = 10)
        {
            if (Session["AD"] == null)
            {
                return RedirectToAction("Index", "AdLogin");
            }
            else
            {
                var user = (UserLogin)Session["AD"];
                var dao = new ProductDao();
                var model = user.Role == 2 ? dao.ListAllPaging2(user.UserID,searchString, page, pageSize): dao.ListAllPaging(searchString, page, pageSize);
                ViewBag.searchString = searchString;
                return View(model);
            }
            
        }
        public ActionResult ListCategory(string searchString, int page = 1, int pageSize = 10)
        {
            var user = (UserLogin)Session["AD"];
            if (Session["AD"] == null || user.Role == 2)
            {
                return RedirectToAction("Index", "AdLogin");
            }
            else
            {
                var dao = new ProductDao();
                var model = dao.ListAllPagingCategory(searchString, page, pageSize);
                ViewBag.searchString = searchString;
                return View(model);
            }

        }
        //CREATE PRODUCT ======================================================================
        [HttpGet]
        public ActionResult CreateProduct()
        {
            if (Session["AD"] == null)
            {
                return RedirectToAction("Index", "AdLogin");
            }
            else
            {
                var user = (UserLogin)Session["AD"];
                db = new AuctionDBContext();
              
                Product product = new Product();
                product.ListLot = db.Lots.ToList();
                if (user.Role == 2)
                {
                    product.ListLot = db.Lots.Where(x => x.HostLot == user.UserID).ToList();
                }
                if (product.ListLot == null)
                {
                    return RedirectToAction("ListProduct");
                }
                return View(product);
            }
            
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult CreateProduct([Bind(Include = "Name,Description,LotID")] Product product, HttpPostedFileBase[] files)
        {
            db = new AuctionDBContext();
            product.ListLot = db.Lots.ToList();
            var user = (UserLogin)Session["AD"];
            if (user.Role == 2)
            {
                product.ListLot = db.Lots.Where(x => x.HostLot == user.UserID).ToList();
            }
            if (product.ListLot == null)
            {
                return RedirectToAction("ListProduct");
            }
            if (ModelState.IsValid)
            {
                product.CreatedAt = DateTime.Now;
                product.CreatedBy = ((UserLogin)Session["AD"]).UserID;
                db.Products.Add(product);
                db.SaveChanges();
                //Lưu từng ảnh nêu có nhập ảnh
                int ProId = db.Products.Max(x => x.ID);//Lấy Id của sản phẩm mới vừa thêm vào
                if (files != null)
                {
                    foreach(HttpPostedFileBase file in files)
                    {
                        ProductsImage img = new ProductsImage();
                
                                 string fileName = UploadFile(file);
                        img.Image = "\\Content\\Images\\Prouduct\\" + fileName;
                        img.ProductId = ProId;
                        db.ProductsImages.Add(img);
                       
                    }
                    db.SaveChanges();

                }


                ViewBag.success = "Tạo mới sản phẩm thành công!";
                return View(product);
            }
            else
            {
                return View(product);
            }
        }
        [HttpGet]
        public ActionResult CreateCategory()
        {
            var user = (UserLogin)Session["AD"];
            if (Session["AD"] == null || user.Role == 2)
            {
                return RedirectToAction("Index", "AdLogin");
            }
            else
            {
         
                return View();
            }

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult CreateCategory(AdCategory adCategory)
        {
            db = new AuctionDBContext();

            if (ModelState.IsValid)
            {
                Category category = new Category();
                category.Name = adCategory.Name;
                category.SiteTile =  FriendlyURL.URLFriendly(adCategory.Name);
                string fileNameCateIcon = UploadFile(adCategory.CateIcon);
                category.CateIcon = "\\Content\\Images\\Prouduct\\" + fileNameCateIcon;
                string fileNameCateImg = UploadFile(adCategory.CateImg);
                category.CateImg = "\\Content\\Images\\Prouduct\\" + fileNameCateImg;
                category.Status = false;
                db.Categories.Add(category);
                db.SaveChanges();
                ViewBag.success = "Tạo mới loại sản phẩm thành công!";
                return View(adCategory);
            }
            else
            {
                return View();
            }
        }
        protected string UploadFile(HttpPostedFileBase file)
        {
            string fileName = null;
            string fileExtension = null;
            string strDate = DateTime.Now.ToString("MM_dd_yyyy_hh_mm_ss");

            SetFilePath();

            fileExtension = Path.GetExtension(file.FileName).Replace(".", "");
            fileName = file.FileName.Substring(file.FileName.LastIndexOf("\\\\") + 1);
            fileName = fileName.Substring(0, fileName.LastIndexOf(fileExtension)) + strDate + "." + fileExtension;

            FilePath = FilePath + fileName;
            file.SaveAs(FilePath);
            return fileName;
        }

        private void SetFilePath()
        {
            FilePath = Server.MapPath("~/Content/Images/Prouduct/");
            if (!Directory.Exists(FilePath))
            {
                Directory.CreateDirectory(FilePath);
            }
        }
      
        
        //public JsonResult GetCate1(int Id)
        //{
        //    db = new AuctionDBContext();
        //    db.Configuration.ProxyCreationEnabled = false;
        //    var cate1 = db.Categories.Where(x => x.ParentId == Id).ToList();
        //    ViewBag.cate1 = new SelectList(cate1, "Id", "Name");
        //    return Json(cate1, JsonRequestBehavior.AllowGet);
        //}
        //EDIT PRODUCT============================================================
        [HttpGet]
        public ActionResult EditProduct(int id)
        {
            if (Session["AD"] == null)
            {
                return RedirectToAction("Index", "AdLogin");
            }
            else
            {
                var user = (UserLogin)Session["AD"];
                db = new AuctionDBContext();
                var product = db.Products.Find(id);              
                product.ListLot = db.Lots.ToList();
                if (user.Role == 2)
                {
                    product.ListLot = db.Lots.Where(x => x.HostLot == user.UserID).ToList();
                }
                if (product.ListLot == null)
                {
                    return RedirectToAction("ListProduct");
                }

                return View(product);
            }
        }
        [HttpGet]
        public ActionResult EditCategory(int id)
        {
            var user = (UserLogin)Session["AD"];

            if (Session["AD"] == null || user.Role == 2)
            {
                return RedirectToAction("Index", "AdLogin");
            }
            else
            {
                db = new AuctionDBContext();
                var Category = db.Categories.Find(id);
                
                return View(Category);
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult EditCategory(Category category, HttpPostedFileBase file1, HttpPostedFileBase file2)
        {

            db = new AuctionDBContext();
            if (Session["AD"] == null)
            {
                return RedirectToAction("Index", "AdLogin");
            }
            if (ModelState.IsValid)
            {
                var editCate = db.Categories.Find(category.ID);
                if (editCate == null)
                    return HttpNotFound();
                editCate.Name = category.Name;
                editCate.SiteTile =  FriendlyURL.URLFriendly(category.Name);
                //Xóa hình ảnh cũ trong bảng ProductImage


                //Sửa thông tin sản phẩm 


                if (file1 != null)
                {
                    string path = Path.Combine(Server.MapPath(editCate.CateImg)); ;

                    if (!Directory.Exists(path))
                    {
                        System.IO.File.Delete(path);
                    }
              
                    string fileName = UploadFile(file1);
                    editCate.CateImg = "\\Content\\Images\\Prouduct\\" + fileName;

Webdaugia/Webdaugia/Areas/Admin/Views/AdProduct/CreateCategory.cshtml
@model Webdaugia.Models.Common.AdCategory
@{
    ViewBag.Title = "CreateCategory";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<h2>Sửa Loại Phiên Đấu</h2>
<div class="box">
    @using (Html.BeginForm("CreateCategory", "AdProduct", FormMethod.Post, new { @area = "Admin", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <div class="col-6 col-sm-12">
            <a href="/admin/adproduct/ListCategory" class="btn btn-info" style="display:inline-block">
                Danh Sách Sản phẩm
            </a>
        </div>


        <div class="col-6  col-sm-12">
            <div class="text-success" style="font-size:large">@ViewBag.success</div>
        </div>
        <div class="col-6  col-sm-12">
            <label>Tên Sản phẩm</label>
            <div class="form_control">
                @Html.TextBoxFor(model => model.Name, htmlAttributes: new { name = "Name", type = "text" })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-6 col-sm-12">
            <label>Hình ảnh </label>
            <div class="form_control">
                @Html.TextBoxFor(model => model.CateImg, htmlAttributes: new { name = "CateImg", type = "file" })
                @*  <input type="file" name="file1" />*@
                @Html.ValidationMessageFor(model => model.CateImg, "", new { @class = "text-danger" })
        
            </div>
        </div>
        <div class="col-6 col-sm-12">
            <label>Icon </label>
            <div class="form_control">
                @Html.TextBoxFor(model => model.CateIcon, htmlAttributes: new { name = "CateImg", type = "file" })
                @*  <input type="file" name="file1" />*@
                @Html.ValidationMessageFor(model => model.CateIcon, "", new { @class = "text-danger" })
      
            </div>
        </div>


        <div class="col-6 col-sm-12">
            <button class="btn btn-success" type="submit">Thêm mới Sản phẩm</button>
        </div>
    }
</div>

Webdaugia/Webdaugia/Areas/Admin/Views/AdProduct/CreateProduct.cshtml
@model Webdaugia.Models.Product
@{
    ViewBag.Title = "CreateProduct";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";

}

<h2>Thêm Sản Phẩm Mới</h2>
<div class="box">
    @using (Html.BeginForm("CreateProduct", "AdProduct", FormMethod.Post, new { @area = "Admin", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <div class="col-6">
            <a href="/admin/adproduct/listproduct" class="btn btn-info" style="display:inline-block">
                Danh Sách Sản phẩm
            </a>
        </div>
        <div class="col-6">
            <div class="text-success" style="font-size:large">@ViewBag.success</div>
        </div>
        <div class="col-6">
            <label>Tên Sản phẩm</label>
            <div class="form_control">
                <input required
                       name="Name"
                       type="text" />
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-6">
            <label>ID Phiên</label>
            <div class="form_control">
                @Html.DropDownListFor(model => model.LotID, new SelectList(Model.ListLot, "Id", "Name"), "--Chọn phiên-- ", new { @Name = "LotID" })
                @Html.ValidationMessageFor(model => model.LotID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-6">
            <label>Hình ảnh </label>
            <div class="form_control">
                <input required type="file" name="files" multiple accept=""/>
            </div>
        </div>
     
        <div class="col-12">
            <label>Mô tả</label>
            <div class="form_control">
                <textarea name="Description">Nhập Mô tả sản phẩm...</textarea>
            </div>
        </div>
        <div class="col-6 col-12">
        
                <button class="btn btn-success" type="submit">Thêm mới Sản phẩm</button>
           
        </div>
    }
</div>
<script>tinymce.init({ selector: 'textarea' });</script>

Webdaugia/Webdaugia/Areas/Admin/Views/AdProduct/EditCategory.cshtml
@model Webdaugia.Models.Category
@{
    ViewBag.Title = "EditCategory";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Sửa Loại Phiên Đấu</h2>
<div class="box">
    @using (Html.BeginForm("EditCategory", "AdProduct", FormMethod.Post, new { @area = "Admin", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <div class="col-6 col-sm-12">
            <a href="/admin/adproduct/ListCategory" class="btn btn-info" style="display:inline-block">
                Danh Sách Sản phẩm
            </a>
        </div>


        <div class="col-6  col-sm-12">
            <div class="text-success" style="font-size:large">@ViewBag.success</div>
        </div>
        <div class="col-6  col-sm-12">
            <label>Tên Sản phẩm</label>
            <div class="form_control">
                <input required
                       name="Name"
                       type="text"
                       value="@Model.Name" />
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-6 col-sm-12">
            <label>Hình ảnh </label>
            <div class="form_control">
                <img src="@Model.CateImg"  style="width:50%; height:auto"/>
                <input type="file" name="file1" multiple accept=".png,.jpg,.jpeg,.gif" />
            </div>
        </div>
        <div class="col-6 col-sm-12">
            <label>Icon </label>
            <div class="form_control">
                <img src="@Model.CateIcon" style="width:50%; height:auto"/>
                <input type="file" name="file2" multiple accept=".png,.jpg,.jpeg,.gif" />
            </div>
        </div>


        <div class="col-6 col-sm-12">
            <button class="btn btn-success" type="submit">Thêm mới Sản phẩm</button>
        </div>
    }
</div>

Webdaugia/Webdaugia/Areas/Admin/Views/AdProduct/EditProduct.cshtml
@model Webdaugia.Models.Product
@{
    ViewBag.Title = "EditProduct";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Sửa Sản Phẩm</h2>
<div class="box">
    @using (Html.BeginForm("EditProduct", "AdProduct", FormMethod.Post, new { @area = "Admin", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <div class="col-6 col-sm-12">
            <a href="/admin/adproduct/listproduct" class="btn btn-info" style="display:inline-block">
                Danh Sách Sản phẩm
            </a>
        </div>


        <div class="col-6  col-sm-12">
            <div class="text-success" style="font-size:large">@ViewBag.success</div>
        </div>
        <div class="col-6  col-sm-12">
            <label>Tên Sản phẩm</label>
            <div class="form_control">
                <input required
                       name="Name"
                       type="text"
                       value="@Model.Name" />
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-6  col-sm-12">
            <label>ID Phiên</label>
            <div class="form_control">
                @Html.DropDownListFor(model => model.LotID, new SelectList(Model.ListLot, "Id", "Name"), "--Chọn phiên-- ", new { @Name = "LotID" })
                @Html.ValidationMessageFor(model => model.LotID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-6">
            <label>Hình ảnh </label>
            <div class="form_control">
                <input type="file" name="files" multiple accept=".png,.jpg,.jpeg,.gif" />
            </div>
        </div>

        <div class="col-12">
            <label>Mô tả</label>
            <div class="form_control">
                <textarea name="Description">@Html.Raw(Model.Description)</textarea>
            </div>
        </div>
        <div class="col-6 col-12">
            <button class="btn btn-success" type="submit">Sửa Sản phẩm</button>
        </div>
    }
</div>
<script>tinymce.init({ selector: 'textarea' });</script>

Webdaugia/Webdaugia/Areas/Admin/Views/AdProduct/ListCategory.cshtml
@model PagedList.IPagedList<Webdaugia.Models.Category>
@using PagedList.Mvc
@{
    ViewBag.Title = "ListCategory";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-12">
        <!-- ORDERS TABLE -->
        <div class="box">
            <div class="box-header title">
                <h2>Danh sách loại phiên đấu giá</h2>

                <div>
                    <a href="/admin/adproduct/CreateCategory" class="btn btn-success" style="display:inline-block">
                        <i class="fa fa-plus-circle"></i>
                        Thêm mới loại phiên đấu giá
                    </a>
                    @*<a href="#" class="btn btn-danger" style="display:inline-block">
                            <i class="fa fa-trash"></i>
                            Xóa SP đã chọn
                        </a>*@
                </div>
            </div>
            <div class="row">
                <div class="col-4 col-sm-12" style="margin-bottom:0">
                    @using (Html.BeginForm("ListCategory", "ADProduct", FormMethod.Get, new { @class = "navbar-search" }))
                    {
                        <input type="text"
                               name="searchString"
                               class="navbar-search-input"
                               placeholder="Tìm kiếm sản phẩm..."
                               value="@ViewBag.searchString" />
                        <button type="submit"><i class="fas fa-search"></i></button>}
                </div>
            </div>
            <div style="overflow-x:scroll">
                <table>
                    <thead>
                        <tr>
                            <th align="center" width="40px">
                                STT
                            </th>
                            <th align="center">Tên Sản Phẩm</th>
                            <th align="center">SileTile </th>
                            <th align="center">Ảnh Loại </th>
                            <th align="center">Icon Loại </th>
                            <th align="center">Hiển thị </th>
                            <th align="center">Thao tác</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{ int count = 1;}

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td align="center">@count</td>
                                @{ count++;}

                                <td align="center">@item.Name</td>
                                <td align="center">@item.SiteTile</td>
                                <td align="center"><img src="@item.CateImg" width="100px" /></td>
                                <td align="center"><img src="@item.CateIcon" width="100px" /></td>



                                @if (item.Status == true)
                                {


                                    <td align="center">
                                        <div class="payment-status payment-paid">
                                            <div class="dot"></div>
                                            <span>Hiển thị</span>
                                        </div>
                                    </td>
                                }
                                else if (item.Status == false)
                                {
                                    <td align="center">
                                        <div class="payment-status payment-pending">
                                            <div class="dot"></div>
                                            <span>Không hiển thị</span>
                                        </div>
                                    </td>
                                }
                                @if (item.Status == false)
                                {
                                    <td align="center">
                                        <a href="/admin/adproduct/EditCategory/@item.ID">
                                            <i class="fas fa-pencil-alt" style="color:dodgerblue"></i>
                                        </a>
                                        <a href="/admin/adproduct/LockOrUnlockCategory/@item.ID" style="padding-left:10px" onclick="return confirm('Bạn có muốn mở khóa loại phiên tên: @item.Name')">
                                            <i class="fas fa-eye" style="color:red"></i>
                                        </a>
                                    </td>
                                }
                                else if (item.Status == true)
                                {
                                    <td align="center">
                                        <a href="/admin/adproduct/EditCategory/@item.ID">
                                            <i class="fas fa-pencil-alt" style="color:dodgerblue"></i>
                                        </a>
                                        <a href="/admin/adproduct/LockOrUnlockCategory/@item.ID" style="padding-left:10px" onclick="return confirm('Bạn có muốn mở khóa loại phiên tên: @item.Name')">
                                            <i class="fas fa-eye-slash" style="color:#04D182"></i>
                                        </a>
                                    </td>
                                }
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
         
            @Html.PagedListPager(Model, page => Url.Action("ListCategory", new { page, @searchString = ViewBag.searchString }))
        </div>
    </div>
</div>

Webdaugia/Webdaugia/Areas/Admin/Views/AdProduct/ListProduct.cshtml
@model PagedList.IPagedList<Webdaugia.Models.Product>
@using PagedList.Mvc
@{
    ViewBag.Title = "ListProduct";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-12">
        <!-- ORDERS TABLE -->
        <div class="box">
            <div class="box-header title">
                <h2>Danh sách sản phẩm</h2>

                <div>
                    <a href="/admin/adproduct/createproduct" class="btn btn-success" style="display:inline-block">
                        <i class="fa fa-plus-circle"></i>
                        Thêm mới sản phẩm
                    </a>
                    @*<a href="#" class="btn btn-danger" style="display:inline-block">
                            <i class="fa fa-trash"></i>
                            Xóa SP đã chọn
                        </a>*@
                </div>
            </div>
            <div class="row">
                <div class="col-4 col-sm-12" style="margin-bottom:0">
                    @using (Html.BeginForm("ListProduct", "AdProduct", FormMethod.Get, new { @class = "navbar-search" }))
                    {
                        <input type="text"
                               name="searchString"
                               class="navbar-search-input"
                               placeholder="Tìm kiếm sản phẩm..."
                               value="@ViewBag.searchString" />
                        <button type="submit"><i class="fas fa-search"></i></button>}
                </div>
            </div>
            <div style="overflow-x:scroll">
                <table>
                    <thead>
                        <tr>
                            <th align="center">
                                STT
                            </th>
                            <th align="center"></th>
                            <th align="center">Tên Sản Phẩm</th>
                            <th align="center">ID Phiên </th>
                            <th align="center">Tên Phiên </th>
                            <th align="center">Ngày tạo</th>
                            <th align="center">Người tạo</th>
                            <th align="center">Thao tác</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model.Count() == 0)
                        {
                            <tr>
                                <td colspan="8" style="
                            text-align: center;
                            font-size: 2rem;">
                                    Hiện chưa có sản phẩm nào
                                </td>
                            </tr>
                        }
                        @{ int count = 1;}
                        @{ var info = System.Globalization.CultureInfo.GetCultureInfo("vi-VN"); }
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@count</td>
                                @{ count++; }
                                @if (@item.ProductsImages.FirstOrDefault().Image != null)
                                {
                                    <td><img src="@item.ProductsImages.FirstOrDefault().Image" width="50px" /></td>
                                }
                                else
                                {
                                    <td>Không có ảnh</td>
                                }

                                <td align="center" >@item.Name</td>
                                <td align="center">@item.Lot.ID</td>
                                <td align="center">@item.Lot.Name</td>
                                <td align="center">@item.CreatedAt</td>
                                <td align="center">@item.CreatedBy</td>
                                <td align="center">
                                    <a href="/admin/adproduct/editproduct/@item.ID" style="padding-left:15px">
                                        <i class="fas fa-pencil-alt" style="color:dodgerblue"></i>
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
           
            @Html.PagedListPager(Model, page => Url.Action("ListProduct", new { page, @searchString = ViewBag.searchString }))
        </div>
    </div>
</div>